export const LOGIN_VENDOR_REQUEST = "LOGIN_VENDOR_REQUEST";
export const LOGIN_VENDOR_SUCCESS = "LOGIN_VENDOR_SUCCESS";
export const LOGIN_VENDOR_FAIL = "LOGIN_VENDOR_FAIL";

export const REGISTER_VENDOR_REQUEST = "REGISTER_VENDOR_REQUEST";
export const REGISTER_VENDOR_SUCCESS = "REGISTER_VENDOR_SUCCESS";
export const REGISTER_VENDOR_FAIL = "REGISTER_VENDOR_FAIL";

export const LOAD_VENDOR_REQUEST = "LOAD_VENDOR_REQUEST";
export const LOAD_VENDOR_SUCCESS = "LOAD_VENDOR_SUCCESS";
export const LOAD_VENDOR_FAIL = "LOAD_VENDOR_FAIL";

export const UPDATE_VENDOR_PROFILE_REQUEST = "UPDATE_VENDOR_PROFILE_REQUEST";
export const UPDATE_VENDOR_PROFILE_SUCCESS = "UPDATE_VENDOR_PROFILE_SUCCESS";
export const UPDATE_VENDOR_PROFILE_FAIL = "UPDATE_VENDOR_PROFILE_FAIL";
export const UPDATE_VENDOR_PROFILE_RESET = "UPDATE_VENDOR_PROFILE_RESET";

export const LOGOUT_VENDOR_SUCCESS = "LOGOUT_VENDOR_SUCCESS";
export const LOGOUT_VENDOR_FAIL = "LOGOUT_VENDOR_FAIL";

export const ALL_VENDORS_REQUEST = "ALL_VENDORS_REQUEST";
export const ALL_VENDORS_SUCCESS = "ALL_VENDORS_SUCCESS";
export const ALL_VENDORS_FAIL = "ALL_VENDORS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
